[package]
name = "{{project-name}}"
authors = ["{{authors}}"]
version = "0.1.0"
edition = "2024"
readme = "README.md"
repository = "https://github.com/{{username}}/{{crate_name}}"
license = "MIT"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
